//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AlbumApp.NET.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Web;

    public partial class Album
    {
        public int AlbumID { get; set; }
        [Required(ErrorMessage = "All fields are mandatory")]
        [DisplayName("Artist")]
        public string ArtistName { get; set; }

        [Required(ErrorMessage = "All fields are mandatory")]

        [DisplayName("Album")]
        public string Album1 { get; set; }

        [Required(ErrorMessage = "All fields are mandatory")]
        public string Description { get; set; }
        [DisplayName("Label")]

        [Required(ErrorMessage = "All fields are mandatory")]
        public string RecordLabel { get; set; }
        [DisplayName("Album Cover")]

        [Required(ErrorMessage = "All fields are mandatory")]
        public string ImagePath { get; set; }

        [NotMapped]
        //[Required(ErrorMessage = "All fields are mandatory")]
        public HttpPostedFileBase ImageUpload { get; set; }

        public Album()
        {
            ImagePath = "~/AppFiles/Images/default.png";
        }
    }
}